[package]
name = "ui"
version = "1.1.3"
authors = ["Delisa Mason <iskanamagus@gmail.com>"]

[dependencies]
cards = "1.1.2"
ncurses = { version = "5.80.0", features = ["wide"] }
libthyme = { path = "../libthyme" }
